cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  7 # use node version 7
branches:
  only: 
  - master # auto build and deploy in only master branch
script: # run after installed
- npm install # install node module
install:
  npm install -g firebase-tools # install firebase-cli
after_success:
- firebase use --token 1/520o4KtxLdXVaiK5VixZgB70Dx6vewBge_g3WfUH7Yw # set firebase token
- firebase use --add infix-to-postfix # set current project
- firebase deploy --non-interactive --token "1/520o4KtxLdXVaiK5VixZgB70Dx6vewBge_g3WfUH7Yw" # deploy project